name: Build
on: [workflow_dispatch]
jobs:
  build-ipa:
    name: build-ipa
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Cleanup
        run: |
          flutter clean
          flutter pub get
          flutter doctor -v
      - name: Build
        run: |
          rm -f .env
          cp .env.example .env
          flutter build ios --release --no-codesign
      - name: Packing IPA
        run: |
          cd build/ios/iphoneos/
          rm -rf Payload
          mkdir Payload
          cp -R Runner.app Payload/
          rm -f retro-sideloading-ios.ipa
          zip -vr retro-sideloading-ios.ipa Payload/
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: ipa-build
          path: build/ios/iphoneos/retro-sideloading-ios.ipa
          compression-level: 0
